# .bashrc

user="$(whoami)"

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
# Source work functions
if [ -f /home/"$user"/.bash_work_functions ]; then
    . /home/"$user"/.bash_work_functions  
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

export EDITOR=vim
export GOROOT=/usr/local/go
export GOPATH=/home/"$user"/go
export PATH=$PATH:$GOPATH/bin:/usr/local/go/bin
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
# User specific aliases and functions

how_in() {
    where="$1"; shift
    IFS=+ curl "https://cht.sh/$where/$*" 
} 


alias tmux='tmux -2'
alias ll='ls -l'
HISTSIZE=50000
HISTFILESIZE=100000
shopt -s histappend

#so as not to be disturbed by Ctrl-S ctrl-Q in terminals:
[[ $- == *i* ]] && stty -ixon

#bash fzf history completion
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
